# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: huronmarron
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: miapp
# serverless.yml
# serverless.yml

service: my-service  # Nombre de tu servicio

provider:
  name: aws
  runtime: nodejs20.x  # Versión de Node.js que deseas utilizar
  lambdaHashingVersion: 20201221
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true
plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello  # La función handler.hello indica que será un archivo handler.js en la carpeta raíz del proyecto
  helloUser:
    handler: handler.helloUser  # La función handler.helloUser indica que será un archivo handler.js en la carpeta raíz del proyecto
    events:
      - http:
          method: GET
          path: user/{name}
  createUser:
    handler: handler.createUser  # La función handler.helloUser indica que será un archivo handler.js en la carpeta raíz del proyecto
    events:
      - http:
          method: POST
          path: user      
          