org: huronmarron
app: miaplicacion
service: mi-servicio-aaron

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: handler.hello
  helloUser:
    handler: handler.helloUser
    events:
      - http:
          method: get
          path: user/{name}
